project:
  type: website
  resources: 
    - "./data/**"
  render: 
    - index.qmd
    - posts/td2-exo1.qmd

website:
  title: "td-lm-ensai"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

