project:
  type: website
  resources: 
    - "./data/**"
  render: 
    - index.qmd
    - posts/td2-exo1.qmd
website:
  title: "td-lm-ensai"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 100px
      gutter-width: 1.5rem
editor: visual

