---
title: "TD 2 - Exercice 5"
lang: fr
author: "Théo Leroy"
date: "26 septembre 2025"
params:
  question_courante: 0
format:
  live-html:
    code-background: true
    toc: true
    page-layout: full
webr:
  render-df: gt-interactive
fig-align: center
filters: 
  - diagram
  - custom-callout
editor: 
  mode: source
  markdown: 
    wrap: 72
diagram:
  engine:
    tikz:
      execpath: lualatex
      header-includes:
        - '\usepackage{tkz-tab}'
custom-callout:    
  answer:
    color: "#CCCCCC"
    icon: true
    icon-symbol: "📝"
    appearance: "default"
    title: "Correction"
---

{{< include ./../_extensions/conditionnal.qmd >}}
{{< include ./../_extensions/r-wasm/live/_knitr.qmd >}}


On se place dans un modèle de régression contenant une constante. On
définit

$$\rho(Y, X) = \sup\limits_{\beta} \textrm{cor}(Y, X\beta)$$

où $\textrm{cor}$ désigne la corrélation empirique. Cette quantité est
donc la corrélation maximale que l’on peut obtenir entre $Y$ et une
combinaison linéaire des variables explicatives.

## Question 1

Montrer que

$$ \textrm{cor}(Y, X\beta) =  \frac{\left(X\hat{\beta}-\overline{Y}\mathbb{1}\right)^{'}\left(X\beta-\overline{X}\beta\mathbb{1}\right)}{\left\| Y-\overline{Y}\mathbb{1}\right\|\left\| X\beta-\overline{X}\beta\mathbb{1}\right\|}$$

où $\hat{\beta}$ est l’estimateur par MCO de la régression de $Y$ sur
$X$, et $\overline{X}$ désigne le vecteur des $p$ moyennes empiriques de
chaque variable explicative.

## Question 2

En déduire que pour tout $\beta$, $\textrm{cor}(Y,X\beta)^2 =  R^2$, où
$R^2$ est le coefficient de corrélation multiple de la régression de $Y$
sur $X$.

## Question 3

Montrer que la borne précédente est atteinte lorsque
$\beta = \hat{\beta}$.

## Question 4

Conclure que $\rho(Y, X)^2 = R^2$ justifiant la terminologie
"coefficient de corrélation multiple".
