---
title: "TD 6 - Exercice 5 - Santé mentale"
lang: fr
author: "Théo Leroy"
date: "5 decembre 2025"
params:
  question_courante: 10
format:
  live-html:
    code-background: true
    toc: true
    page-layout: full
webr:
  render-df: gt-interactive
  resources:
    - ./../../data/Mental.txt
  packages:
      - dplyr
      - readr
      - ggplot2
      - tidyr
      - VGAM
editor: 
  mode: source
  markdown: 
    wrap: 72
fig-align: center
filters: 
  - custom-callout
custom-callout:    
  answer:
    color: "#CCCCCC"
    icon: true
    icon-symbol: "📝"
    appearance: "default"
    title: "Correction"
---

{{< include ./../../_extensions/conditionnal.qmd >}}
{{< include ./../../_extensions/r-wasm/live/_knitr.qmd >}}

On considère les données `mental`, contenues dans le fichier
`Mental.txt`. Ce jeu de données, de taille $n = 40$,
est extrait d’une étude sur la santé mentale d’adultes vivant dans le comté américain
d’Alachua, en Floride. Il contient trois variables :

- Une variable $\texttt{impair}$ décrivant l’état mental de la personne concernée, de 1 (sain) à
4 (en mauvaise santé),
- Une variable $\texttt{ses}$ qui vaut 1 si la personne a un statut socio-économique élevé, 0
sinon,
- Une variable $\texttt{life}$ mesurant le nombre et l’intensité des bouleversements qu’a connus
la personne au cours des trois dernières années, de 0 (aucun changement) à 9
(changements très importants).


Le but de l’exercice est de modéliser la variable $\texttt{impair}$.

## Question 1

Importer les données sous {{< iconify logos:r-lang >}}. La variable $\texttt{ses}$
est-elle qualitative ou quantitative ?
Même question pour la variable $\texttt{life}$.
Changer leur classe sous {{< iconify logos:r-lang >}} si besoin.

::: {.content-visible when-meta="is_answer_print_1"}

::: answer

Importons le fichier de données `Mental.txt` en {{< iconify logos:r-lang >}} sous forme de
`data.frame`.

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
data_mental <- read.csv(
  file = 'data/Mental.txt',
  sep = " ",
  header = TRUE,
  colClasses = c("factor", "integer", "integer")
)
data_mental$impair <- as.ordered(data_mental$impair)
data_mental
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
data_mental <- readr::read_delim(
  file = "data/Mental.txt",
  col_types = readr::cols(
    readr::col_factor(levels = c("1", "2", "3", "4"), ordered = TRUE),
    readr::col_integer(),
    readr::col_integer()
  ),
  delim = " "
)
data_mental
```
:::

La variable $\texttt{ses}$ (statut socio-économique) est qualitative. On peut la
charger comme `factor` ou comme `integer` car cette variable ne comporte
que deux modalités.

À l'inverse, on peut voir la variable $\texttt{life}$ comme quantitative. On
suppose que l'accroissement d'une unité de cette variable a du sens et
correspond à une augmentation de la fréquence d'évènements troublants
pour un individu. Considérer la variable $\texttt{life}$ comme qualitative ne
serait pas une erreur mais ferait exploser le nombre de regresseurs dans
la modélisation alors qu'il n'y a que 40 observations.

:::

:::

## Question 2

Effectuer une petite étude descriptive pour identifier un lien éventuel entre la variable
$\texttt{impair}$ et les autres variables du jeu de données.

::: {.content-visible when-meta="is_answer_print_2"}

::: answer

**Lien entre $\texttt{ses}$ et $\texttt{impair}$**

::: {.panel-tabset group="language"}
#### Base R

```{webr}
#| envir: baser
#| autorun: true
# Création d'une table de contingence pour les proportions
prop_data <- as.data.frame(prop.table(table(data_mental$impair, data_mental$ses), margin = 1))
names(prop_data) <- c("impair", "ses", "proportion")

# Création des barres empilées avec proportions
barplot_data <- table(data_mental$impair, data_mental$ses)

barplot(
  height = t(prop.table(barplot_data, margin = 1)), # Calcul des proportions par groupe
  beside = FALSE, # Empilé
  col = c("#949FA6", "#F24B4B"), # Couleurs
  xlab = "Proportion", 
  ylab = "État mental",
  horiz = TRUE, # Orientation horizontale
  legend.text = c("Faible", "Élevé"), # Légende
  args.legend = list(x = "bottom", inset = 0.05, title = "Statut socio-économique") # Position de la légende
)
```

#### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
ggplot2::ggplot(
  data = data_mental,
  mapping = ggplot2::aes(y = impair, fill = as.factor(ses), by = impair)
) +
  ggplot2::geom_bar(position = "fill") +
  ggplot2::geom_text(
    mapping = ggplot2::aes(label = after_stat(count)),
    stat = "count",
    position = position_fill(vjust = 0.5)
  ) +
  ggplot2::labs(x = "Proportion", y = "État mental") +
  ggplot2::scale_fill_manual(
    values = c("1"="#F24B4B", "0"="#949FA6"),
    labels = c("1"="Élevé", "0"="Faible"),
    name = "Statut socio-économique"
  ) +
  ggplot2::theme_light() +
  ggplot2::theme(legend.position = "bottom")
```
:::

**Lien entre $\texttt{life}$ et $\texttt{impair}$**

::: {.panel-tabset group="language"}
#### Base R

```{webr}
#| envir: baser
#| autorun: true
boxplot(
  life ~ impair, 
  data = data_mental, 
  col = "#F2F2F2", 
  xlab = "État mental", 
  ylab = "Score de troubles vécus life", 
  border = "black"
)
```

#### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
ggplot2::ggplot(
  data = data_mental,
  mapping = ggplot2::aes(x = impair, y = life, group = impair)
) +
  ggplot2::geom_boxplot(fill = "#F2F2F2") +
  ggplot2::labs(x = "État mental", y = "Score de troubles vécus life") +
  ggplot2::scale_x_discrete(
    labels = c(
      "1"="Sain",
      "2"="Plutôt sain",
      "3"="Plutôt en mauvaise santé",
      "4"="En mauvaise santé"
      )
  ) +
  ggplot2::theme_light() 
```
:::

Ce graphique illustre une relation empirique positive entre les
variables $\texttt{life}$ et $\texttt{impair}$. Plus la fréquence et l'intensité des
bouleversements vécus sont importants et plus les personnes sont dans
une situation de mauvaise santé mentale.

:::

:::

## Question 3
Pour commencer, on décide d’ignorer le fait que la variable impair est ordinale et de la
modéliser par un modèle logistique multinomial (sans interaction entre les variables).
Ecrire mathématiquement ce modèle. Combien a-t-il de coefficients à estimer ?

::: {.content-visible when-meta="is_answer_print_3"}

::: answer

Le modèle de régression logistique multinomial s'écrit :

$$
\begin{align*}
\texttt{impair}&|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}) \sim \mathcal{M}( \\
&n=1, \\
&1-\sum\limits_{k=2}^4\mathbb{P}(\texttt{impair}= k|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}= 2|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}= 3|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}= 4|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))) \\
\end{align*}
$$
On estime les rapports en prennant une des modalités comme référence (par défaut, {{< iconify logos:r-lang >}} choisit la première c'est à dire la modalité $\texttt{impair}=1$):

$$
\forall \ k \in \{2, \ 3,\ 4 \}, \ \ln\left(\frac{\mathbb{P}(\texttt{impair}= k|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))}{\mathbb{P}(\texttt{impair}= 1|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))}\right)=\alpha_0^{(k)}+\alpha_1^{(k)}x_{\texttt{ses}}+\alpha_2^{(k)}x_\texttt{life}
$$

On estime donc 9 coefficients (3 par rapport).

:::

:::


## Question 4

Estimer ce modèle à l’aide de la fonction `vglm` du package `VGAM`, en choisissant comme
modalité de référence `impair=1`, et sélectionner le meilleur sous-modèle possible.

::: {.content-visible when-meta="is_answer_print_4"}

::: answer

Nous allons estimer ce modèle, toutefois, les fonctionnalités {{< iconify logos:r-lang >}}
de base ne permettent pas d'estimer ce modèle directement avec une fontion comme
`lm` ou `glm`. Le cours nous invite, par exemple, à utiliser le package
`VGAM` et la fonction `vglm` en son sein.

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
modele_q4_full <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ life + ses,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)
summary(modele_q4_full)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
modele_q4_full <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ life + ses,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)
summary(modele_q4_full)
```
:::

On retrouve bien les 9 coefficients attendus. À première vue, la variable `ses` (statut socio-économique) ne semble pas significative.

On estime les sous modèles possibles :

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
modele_q4_ses <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ ses,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)
modele_q4_life <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ life,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)

data.frame(
  `Modèle`=c("Avec impair et ses", "Avec ses uniquement", "Avec life uniquement"),
  AIC = sapply(X=c(modele_q4_full, modele_q4_ses, modele_q4_life), FUN = AIC),
  BIC = sapply(X=c(modele_q4_full, modele_q4_ses, modele_q4_life), FUN = BIC)
)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
modele_q4_ses <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ ses,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)
modele_q4_life <- VGAM::vglm(
  formula = factor(impair, ordered = FALSE) ~ life,
  family = VGAM::multinomial(refLevel="1"),
  data = data_mental
)

data.frame(
  `Modèle`=c("Avec life et ses", "Avec ses uniquement", "Avec life uniquement"),
  AIC = sapply(X=c(modele_q4_full, modele_q4_ses, modele_q4_life), FUN = AIC),
  BIC = sapply(X=c(modele_q4_full, modele_q4_ses, modele_q4_life), FUN = BIC)
)
```
:::

:::

:::


## Question 5

On souhaite à présent exploiter le fait que la variable impair est ordonnée. Écrire mathématiquement le modèle de régression logistique cumulatif proportionnel
sans terme d’interaction liant $\texttt{impair}$ à $\texttt{ses}$ et $\texttt{life}$,
et permettant d’estimer les probabilités que
$\texttt{impair} = 1, \ \texttt{impair} \leq 2$ et $\texttt{impair} \leq 3$.
Combien ce modèle a-t-il de coefficients ?

::: {.content-visible when-meta="is_answer_print_5"}

::: answer

La loi décrivant l'état mental d'un individu conditionnellement à son
statut économique ($\texttt{ses}$) et le nombre et l'intensité des
bouleversements qu'il a connu au cours des trois dernières années
($\texttt{life}$) est une loi de multinomiale.

Le modèle de régression logistique cumulatif avec structure
proportionnelle s'écrit :

$$
\begin{align*}
\texttt{impair}&|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}) \sim \mathcal{M}( \\
&n=1, \\
&\mathbb{P}(\texttt{impair}\leq 1|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}\leq 2|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))-\mathbb{P}(\texttt{impair}\leq 1|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}\leq 3|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))-\mathbb{P}(\texttt{impair}\leq 2|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&1 - \mathbb{P}(\texttt{impair}\leq 3|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))) \\
\end{align*}
$$

avec

$$
\forall\ k \in \{1,2,3\}, \ \textrm{logit}\left(\mathbb{P}(\texttt{impair}\leq k | (\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))\right) = \beta_0^{(k)}+\beta_1x_{\texttt{ses}}+\beta_2x_\texttt{life}
$$

Il y a 5 paramètres à estimer : $\beta_0^{(1)}$, $\beta_0^{(2)}$,
$\beta_0^{(3)}$, $\beta_1$ et $\beta_2$.

:::

:::

## Question 6

Estimer les coefficients de ce modèle à l’aide de la fonction `vglm` du package
`VGAM`, associée à l’option `family=cumulative(parallel=TRUE)`. Contrôler que
le nombre de coefficients est bien celui attendu.

::: {.content-visible when-meta="is_answer_print_6"}

::: answer

Nous allons estimer ce modèle avec `vglm` du package `VGAM`.

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
modele_q6 <- VGAM::vglm(
  formula = impair ~ ses + life,
  family = VGAM::cumulative(parallel = TRUE),
  data = data_mental
)
summary(modele_q6)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
modele_q6 <- VGAM::vglm(
  formula = impair ~ ses + life,
  family = VGAM::cumulative(parallel = TRUE),
  data = data_mental
)
summary(modele_q6)
```
:::

On peut lire les valeurs des 5 coefficients attendus dans la colonne
`Estimate` (3 pour les constantes de chaque probabilité cumulée et 2
associées à chaque régresseur).

:::

:::

## Question 7

Y a-t-il une influence du statut socio-économique sur l’état de santé mentale au seuil
5 % ? Et au seuil 10 % ?

::: {.content-visible when-meta="is_answer_print_7"}

::: answer

D'après la sortie obtenue à la [question 6](#question-6) et les p-valeur
des tests de Wald, le coefficient $\beta_1$ est non significatif au
seuil d'erreur 5 % mais il est significatif au seuil 10 %.

Toutefois, l'effectif relativement faible (40 personnes), ce qui limite la puissance statistique des tests. En d’autres termes, l’absence de significativité pourrait simplement provenir d’un manque de données. Sur le plan médical, on ne peut donc pas écarter totalement l’éventuelle influence de cette variable sur l’état de santé mentale.

:::

:::

## Question 8

Peut-on proposer un modèle plus simple ?

::: {.content-visible when-meta="is_answer_print_8"}

::: answer

Au vu de la question précédente, on peut essayer de retirer la variable $\texttt{ses}$ :

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
modele_q8 <- VGAM::vglm(
  formula = impair ~ life,
  family = VGAM::cumulative(parallel = TRUE),
  data = data_mental
)
summary(modele_q8)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
modele_q8 <- VGAM::vglm(
  formula = impair ~ life,
  family = VGAM::cumulative(parallel = TRUE),
  data = data_mental
)
summary(modele_q8)
```
:::

On peut faire un test de rapport de vraisemblance comparant ce modèle au modèle avec la variable $\texttt{ses}$.

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
anova(modele_q8, modele_q6, type = "I")
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
anova(modele_q8, modele_q6, type = "I")
```
:::

Au seuil de 5 %, on est donc amené à privilégier ce modèle plus simple.

Cependant, compte tenu de la p-value proche du seuil et du faible effectif de l’étude, ce choix peut être questionné.

:::

:::


## Question 9

On souhaite vérifier que le modèle à odds proportionnel est adéquat par rapport
au modèle de régression logistique cumulatif (sans interaction). Écrire l’expression
mathématique de ce modèle, l’estimer et comparer au modèle à odds proportionnel.

::: {.content-visible when-meta="is_answer_print_9"}

::: answer

Le modèle de régression logistique cumulatif sans structure
proportionnelle et sans terme d'intéraction s'écrit :

$$
\begin{align*}
\texttt{impair}&|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}) \sim \mathcal{M}( \\
&n=1, \\
&\mathbb{P}(\texttt{impair}\leq 1|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}\leq 2|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))-\mathbb{P}(\texttt{impair}\leq 1|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&\mathbb{P}(\texttt{impair}\leq 3|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))-\mathbb{P}(\texttt{impair}\leq 2|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life})), \\
&1 - \mathbb{P}(\texttt{impair}\leq 3|(\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))) \\
\end{align*}
$$

avec pour tout $k \in \{1,2,3\}$

$$
 \textrm{logit}\left(\mathbb{P}(\texttt{impair}\leq k | (\texttt{ses}=x_\texttt{ses},\texttt{life}=x_\texttt{life}))\right) = \gamma_0^{(k)}+\gamma_1^{(k)}x_{\texttt{ses}}+\gamma_2^{(k)}x_\texttt{life}
$$

Il y a 9 paramètres à estimer : $\gamma_0^{(1)}$, $\gamma_0^{(2)}$,
$\gamma_0^{(3)}$, $\gamma_1^{(1)}$, $\gamma_1^{(2)}$, $\gamma_1^{(3)}$,
$\gamma_2^{(1)}$, $\gamma_2^{(2)}$ et $\gamma_2^{(3)}$.

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
modele_q9 <- VGAM::vglm(
  formula = impair ~ ses + life,
  family = VGAM::cumulative(parallel = FALSE),
  data = data_mental
)
summary(modele_q9)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
modele_q9 <- VGAM::vglm(
  formula = impair ~ ses + life,
  family = VGAM::cumulative(parallel = FALSE),
  data = data_mental
)
summary(modele_q9)
```
:::

À l'image de la [question 8](#question-8), on peut faire un test du
rapport de vraisemblance entre ces deux modèles emboités.

L'hypothèse nulle est
$H_0: \gamma_1^{(1)}=\gamma_1^{(2)}=\gamma_1^{(3)}$ et
$\gamma_2^{(1)}=\gamma_2^{(2)}=\gamma_2^{(3)}$.

Les valeurs de la statistique de test et le quantile de comparaison sont
:

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
summary(modele_q6)@criterion$deviance - summary(modele_q9)@criterion$deviance
qchisq(0.95,4)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
summary(modele_q6)@criterion$deviance - summary(modele_q9)@criterion$deviance
qchisq(0.95,4)
```
:::

Quatre coefficients sont contraints dans le modèle avec structure
proportionnelle.

On ne rejette pas $H_0$ car la statistique de test est inférieure au
quantile $q_{0.95}^{\chi^2(4)}$.

Ainsi, le modèle avec la structure non proportionnelle n'est pas
significativement meilleur.

::: {.callout-note collapse="true"}
### Alternative avec la fonction `anova`

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
anova(modele_q6, modele_q9, type = "I")
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
anova(modele_q6, modele_q9, type = "I")
```
:::


:::

:::

:::


## Question 10

Conclure sur la modélisation de la variable $\texttt{impair}$.


::: {.content-visible when-meta="is_answer_print_10"}

::: answer


Le modèle à odds proportionnels est le plus simple et se révèle préférable au modèle cumulatif (voir question précédente).

::: {.panel-tabset group="language"}
### Base R

```{webr}
#| envir: baser
#| autorun: true
AIC(modele_q6)
AIC(modele_q9)
BIC(modele_q6)
BIC(modele_q9)
```

### Tidyverse

```{webr}
#| envir: tdv
#| autorun: true
AIC(modele_q6)
AIC(modele_q9)
BIC(modele_q6)
BIC(modele_q9)
```
:::

Les critères AIC et BIC confirment également qu’il est supérieur au modèle multinomial. Nous retenons donc ce modèle pour expliquer $\texttt{impair}$.

Reste à décider s’il faut inclure la variable ses dans l’analyse, décision pour laquelle une expertise métier serait précieuse.

:::

:::
